apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hr-app
  name: hr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hr-app
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        resources: {}
status: {}
